version: "3"
services:
  builder:
    image: builder
    build: .
  demo1:
    build: ./packages/demo1
    image: demo1:latest
    ports:
      - "9001:9001"
  demo2:
    build: ./packages/demo2
    image: demo2:latest
    ports:
      - "9002:9002"
